name: escuelas_commons
description: Paquete que contiene configuraciones en comun con los otros proyectos dentro de escuelas 2
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  escuelas_client:
    git:
      url: https://github.com/juanjosegarcia98/escuelas_client

  freezed_annotation: ^2.4.1
  rolemissions:
    git:
      url: https://github.com/Rodsevich/rolemissions

dev_dependencies:
  # archivos auto generados
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
